WORKING_DIR = .
COMPONENT = $(WORKING_DIR)/simulations/tos_apps/bareBenchmark/Benchmark
PFLAGS += -I$(WORKING_DIR)/simulations/tos_apps/bareBenchmark
ifneq ($(findstring telosb,$(MAKECMDGOALS)),)
	PFLAGS += -Dtelosb
endif
ifneq ($(findstring pc,$(MAKECMDGOALS)),)
	PFLAGS += -Dpc
endif
ifneq ($(findstring mica2,$(MAKECMDGOALS)),)
	PFLAGS += -Dmica2
endif
MSG_SIZE = 50
include $(TOSROOT)/tools/make/Makerules

