WORKING_DIR = .
COMPONENT = $(WORKING_DIR)/apps/hvac/HVAC
PFLAGS += -I$(WORKING_DIR)/apps/hvac
PFLAGS += -I$(WORKING_DIR)/services/mutualExclusion
ifneq ($(findstring telosb,$(MAKECMDGOALS)),)
	PFLAGS += -Dtelosb
endif
ifneq ($(findstring pc,$(MAKECMDGOALS)),)
	PFLAGS += -Dpc
endif
ifneq ($(findstring mica2,$(MAKECMDGOALS)),)
	PFLAGS += -Dmica2
endif
MSG_SIZE = 119
include $(TOSROOT)/tools/make/Makerules


