/***
 * * Automatically generated by HuffmanCompression on 16/09/2008 18:39:54
 * * DO NOT EDIT! 
 ***/

uint16_t returnHuffmanCode_2(uint8_t symbol) {

  return symbol;
}

uint8_t returnHuffmanBitLen_2(uint8_t symbol) {

  return 8;
}

