#!/bin/sh
cd sinkNode && \
make clean && make tmote && \
cd ../ltNode && \
make tmote && \
cd ../sinkNode && \
make tmote && \
cd ../java && \
ant clean && ant && \
cd ../ltNode && \
make tmote && \
cd ..
