# the main component reference
COMPONENT ?= Test_LIS3L02AL


# including standard rules
include $(MAKERULES)



#defining baudrate
DEFAULT_BAUDRATE = 57600


# the moteiv root directory
#MOTEIV_DIR ?= ../../



